### ISSUE TITLE
Failed connection [400] - [Unsupported upgrade request.]

### ISSUE THREAD

**Issue by Atlogit** [inception-project/inception-external-recommender-v2#24]
When the app is run on a remote cloud instance, trying to access (with INCEpTION) gives: 
Failed: Request was not successful: [400] - [Unsupported upgrade request.]

The common fix doesn't work (uninstall uvicorn and install uvicorn[standard]).

**Comment by reckart** [comment]
@Atlogit You are aware that the support for the v2 external recommender has not yet been merged into INCEpTION? https://github.com/inception-project/inception/pull/2313

Current version of INCEpTION are only compatible with v1: https://github.com/inception-project/inception-external-recommender

**Comment by Atlogit** [comment]
I am now :)
Thank you.
Any advice on how experiment with it?

**Comment by reckart** [comment]
With the v1 external recommender service? It has a bunch of pre-implemented integrations of different tools that you can try out, there is a video, there is a notebook - I think there's plenty of stuff to get started with.

**Comment by Atlogit** [comment]
I meant with v2. You show in the description a version of INCEpTION that has that. How can one try the V2? 
I'm not sure I understand the status of this repo/project.

**Comment by reckart** [comment]
The status is "experimental" and currently somewhat dormant.

You could check out the pull request mentioned above, build it and add `recommender.external.v2.enabled=true` to the `settings.properties` if you want to have a version of INCEpTION that can speak "v2".

There is also a unit test in the PR which can talk to a v2 service instance:

https://github.com/inception-project/inception/blob/396436391e59c0d375d972db8bee1a5107f8f598/inception/inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v2/api/ExternalRecommenderV2ApiTest.java#L40
